==============================================================================================================================
                Livros

### Recupera Todos os Regristros Em Livros
GET http://localhost:8080/livro/todos HTTP/1.1
Authorization: Basic root:root

### Recupera Lista De Livros Filtrados Por Nome
@varLivro= novo
GET http://localhost:8080/livro/buscar/nome?nome={{varLivro}} HTTP/1.1
Authorization: Basic root:root

### Recupera Livro Filtrado Por ISBN
@varIsbn= 667244404
GET http://localhost:8080/livro/buscar/isbn?isbn={{varIsbn}} HTTP/1.1
Authorization: Basic root:root

==============================================================================================================================
                Fornecedor

### Recupera Todos os Regristros Em Fornecedor
GET http://localhost:8080/fornecedor/todos HTTP/1.1
Authorization: Basic root:root

### Recupera os Regristros Em Fornecedor Por Razão Social
@varRazaosocial = novo 2
GET http://localhost:8080/fornecedor/buscar/razaosocial?razaosocial={{varRazaosocial}} HTTP/1.1
Authorization: Basic root:root

### Recupera os Regristros Em Fornecedor Por CNPJ
@varCnpj = 12.333.280/0001-39
GET http://localhost:8080/fornecedor/buscar/cnpj?cnpj={{varCnpj}} HTTP/1.1
Authorization: Basic root:root

==============================================================================================================================
                Usuario

### Recupera Todos os Regristros Em Usuario
GET http://localhost:8080/usuario/todos HTTP/1.1
Authorization: Basic root:root

### Recupera Os Regristros Em Usuario por CPF
@varCpf= 437.507.100-15
GET http://localhost:8080/usuario/busca/cpf?cpf={{varCpf}} HTTP/1.1
Authorization: Basic root:root

### Recupera Os Regristros Em Usuario por Nome
@varUsuario= Anderson
GET http://localhost:8080/usuario/busca/nome?nome={{varUsuario}} HTTP/1.1
Authorization: Basic root:root

==============================================================================================================================
                Pedido
                
### Recupera Todos os Regristros Em Pedido
GET http://localhost:8080/pedido/todos HTTP/1.1
Authorization: Basic root:root


==============================================================================================================================
                Relatórios

### Gera Relatório de Vendas
GET http://localhost:8080/relatorio/vendas HTTP/1.1
Authorization: Basic root:root

### Gera Relatório Estoque de Livros
GET http://localhost:8080/relatorio/estoquelivro HTTP/1.1
Authorization: Basic root:root

