### Aletara o Atributo vendaCancelada Para True

@idPedido=7
PATCH  http://localhost:8080/pedido/cancelar/pedido/{{idPedido}} HTTP/1.1
Content-Type: application/json
Authorization: Basic root:root

{
    "idUsuario": 3
}

### Adiciona livros ao estoque

@idLivro=2
PATCH http://localhost:8080/livro/adicionarestoque/{{idLivro}} HTTP/1.1
Content-Type: application/json
Authorization: Basic root:root

{
    "quantLivros": 10
}