### Recupera Todos os Regristros Em Livros
GET http://localhost:8080/livro/todos HTTP/1.1

### Recupera Lista De Livros Filtrados Por Nome
@varNome= novo
GET http://localhost:8080/livro/buscar/nome?nome={{varNome}} HTTP/1.1

### Recupera Todos os Regristros Em Fornecedor
GET http://localhost:8080/fornecedor/todos HTTP/1.1

### Recupera os Regristros Em Fornecedor Por Razão Social
@varRazaosocial = teste t
GET http://localhost:8080/fornecedor/buscar/razaosocial?razaosocial={{varRazaosocial}} HTTP/1.1

### Recupera os Regristros Em Fornecedor Por CNPJ
@varCnpj = 1123123
GET http://localhost:8080/fornecedor/buscar/cnpj?cnpj={{varCnpj}} HTTP/1.1

### Recupera Todos os Regristros Em Usuario
GET http://localhost:8080/usuario/todos HTTP/1.1

### Recupera Os Regristros Em Usuario por CPF
@varCpf= 2351-23
GET http://localhost:8080/usuario/busca/cpf?cpf={{varCpf}} HTTP/1.1

### Recupera Os Regristros Em Usuario por Nome
@varNome= Anderson
GET http://localhost:8080/usuario/busca/nome?nome={{varNome}} HTTP/1.1

### Recupera Todos os Regristros Em Pedido
GET http://localhost:8080/pedido/todos HTTP/1.1

### Gera Relatório de Vendas
GET http://localhost:8080/relatorio/vendas HTTP/1.1

### Gera Relatório Estoque de Livros
GET http://localhost:8080/relatorio/estoquelivro HTTP/1.1

