### Aletara o Atributo vendaCancelada Para True

@idPedido=5
@idUsuario=1
PATCH  http://localhost:8080/pedido/cancelar/pedido/{{idPedido}}/usuario/{{idUsuario}} HTTP/1.1


### Adiciona livros ao estoque

@idLivro=1
PATCH http://localhost:8080/adicionarestoque/{{idLivro}} HTTP/1.1