### Salva Um Registro Em Livro
POST http://localhost:8080/livro HTTP/1.1
Content-Type: application/json

{
  "descricao": "Livro 5",
  "isbn": "5-5-5-5",
  "nome": "novo3",
  "quantLivros": "20",
  "tagEstoque": "2b3",
  "valorRecebimento": "30",
  "valorVenda": "50",
  "idFornecedor":2
}

### Salva Um Registro Em Fornecedor
POST http://localhost:8080/fornecedor HTTP/1.1
Content-Type: application/json

{
  "endereco": "Novo Fornecedor 2",
  "email": "a@b",
  "telefone": "123-213",
  "observacao": "bla",
  "nomeFantasia": "Novidade",
  "razaoSocial": "novo 2",
  "cnpj": "22222222",
  "insEstadual": "MG"
}

### Salva Um Registro Em Usuario
POST http://localhost:8080/usuario HTTP/1.1
Content-Type: application/json

{
	"endereco": "rua Teste 4",
	"email": "t@t",
	"telefone": "123-321",
	"observacao": "testando",
	"nome": "Anderson Nardi2",
	"rg": "123-62324",
	"cpf": "2351-232324",
	"genero": 0,
	"perfil": 1,
	"dataDeNas": "02/02/2222",
	"dataDeCadastro": "12/05/2225"
}

### Salva Um Registro Em Pedido
POST http://localhost:8080/pedido HTTP/1.1
Content-Type: application/json

{
  "valorVenda": "100",
  "enderecoEntrega": "rua da entrega",
  "formaDePgto": "cartao",
  "parcela": "2",
  "dataVenda": "03/01/2014",
  "dataPgto": "03/02/2014",
  "dataEntrega": "16/02/2014",
  "idUsuario": 3,
  "listaLivro": [
    {
      "idLivro": 4,
      "quantidade": 1
    },
    {
      "idLivro": 2,
      "quantidade": 3
    }
  ]
}

### Aletara o Atributo vendaCancelada Para True
POST http://localhost:8080/pedido/cancelar/pedido HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "usuario":"administrador"
}
