### Altera Um Registro Em Livro
@idLivro = 4
PUT http://localhost:8080/livro/atualizar/{{idLivro}} HTTP/1.1
Content-Type: application/json

{
  "descricao": "Livro 5 - Alterado Agora mesmo5",
  "isbn": "74/1-1/1-",
  "nome": "novo5",
  "quantLivros": "20",
  "tagEstoque": "2b3",
  "valorRecebimento": "30",
  "valorVenda": "20",
  "idFornecedor":6
}

### Altera Um Registro Em Usuário
@idUsuario = 1
PUT http://localhost:8080/usuario/{{idUsuario}} HTTP/1.1
Content-Type: application/json

{
	"endereco": "Testando Alteração1 Nova",
	"email": "altt@t",
	"telefone": "1233-321",
	"observacao": "testando2",
	"nome": "Testino2",
	"rg": "123-6221",
	"cpf": "2351-23221",
	"genero": 3,
	"perfil": 0,
	"dataDeNas": "02/02/2223",
	"dataDeCadastro": "12/05/2226"
}